"""
NexLink Server — Session Manager
==================================
Manages WebSocket session lifecycle: open, close, and query.

Session Lifecycle:
  OPEN:    open_session(device_id, client_ip, user_agent)
             → creates AgentSession row with is_active=True
             → returns session_id (UUID)
  CLOSE:   close_session(session_id, reason, code)
             → updates is_active=False, sets disconnected_at, duration
  QUERY:   get_session(), list_sessions(), active_session_for_device()

Session ID:
  Generated by the server (uuid4). Shared with the agent in the auth response.
  The agent includes session_id in heartbeat and WebSocket messages so the
  server can correlate all activity within a single connection.
"""
from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone

from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from server.core.exceptions import SessionNotFoundError
from server.db.models.session import AgentSession
from server.schemas.session import SessionListResponse, SessionSchema, SessionSummarySchema

logger = logging.getLogger(__name__)


class SessionManager:
    """Session CRUD operations."""

    async def open_session(
        self,
        device_id: uuid.UUID,
        db: AsyncSession,
        client_ip: str | None = None,
        user_agent: str | None = None,
    ) -> uuid.UUID:
        """
        Create a new active session for a device.

        Returns the server-generated session_id UUID.
        The session_id is shared with the agent in the token/connect response.
        """
        session = AgentSession(
            device_id=device_id,
            client_ip=client_ip,
            user_agent=user_agent,
            is_active=True,
        )
        db.add(session)
        await db.flush()  # populate session.session_id
        logger.info(
            "Session opened: session_id=%s device_id=%s",
            session.session_id, device_id,
        )
        return session.session_id

    async def close_session(
        self,
        session_id: uuid.UUID,
        db: AsyncSession,
        reason: str = "normal_close",
        code: int = 0,
    ) -> None:
        """
        Close an active session. Sets is_active=False and records duration.
        Safe to call even if session is already closed.
        """
        result = await db.execute(
            select(AgentSession).where(AgentSession.session_id == session_id)
        )
        session = result.scalar_one_or_none()
        if session is None:
            logger.warning("close_session: session %s not found", session_id)
            return

        if not session.is_active:
            logger.debug("close_session: session %s already closed", session_id)
            return

        session.close(reason=reason, code=code)
        await db.flush()

        logger.info(
            "Session closed: session_id=%s duration=%ss reason=%s",
            session_id, session.duration_seconds, reason,
        )

    async def get_session(
        self,
        session_id: uuid.UUID,
        db: AsyncSession,
    ) -> AgentSession:
        """Fetch a session by session_id. Raises SessionNotFoundError if missing."""
        result = await db.execute(
            select(AgentSession).where(AgentSession.session_id == session_id)
        )
        session = result.scalar_one_or_none()
        if session is None:
            raise SessionNotFoundError(f"Session {session_id} not found")
        return session

    async def active_session_for_device(
        self,
        device_id: uuid.UUID,
        db: AsyncSession,
    ) -> AgentSession | None:
        """Return the current active session for a device, or None."""
        result = await db.execute(
            select(AgentSession).where(
                AgentSession.device_id == device_id,
                AgentSession.is_active == True,
            ).order_by(AgentSession.connected_at.desc())
            .limit(1)
        )
        return result.scalar_one_or_none()

    async def close_all_device_sessions(
        self,
        device_id: uuid.UUID,
        db: AsyncSession,
        reason: str = "device_offline",
    ) -> int:
        """
        Close all active sessions for a device.
        Called when device goes offline or is deactivated.
        Returns the number of sessions closed.
        """
        result = await db.execute(
            select(AgentSession).where(
                AgentSession.device_id == device_id,
                AgentSession.is_active == True,
            )
        )
        sessions = result.scalars().all()
        for s in sessions:
            s.close(reason=reason, code=2)  # code 2 = server shutdown/forced
        await db.flush()

        if sessions:
            logger.info(
                "Closed %d active session(s) for device %s (reason=%s)",
                len(sessions), device_id, reason,
            )
        return len(sessions)

    async def list_sessions(
        self,
        db: AsyncSession,
        page: int = 1,
        per_page: int = 20,
        device_id: uuid.UUID | None = None,
        active_only: bool = False,
    ) -> SessionListResponse:
        """Paginated session list with optional filters."""
        query = select(AgentSession)
        if device_id:
            query = query.where(AgentSession.device_id == device_id)
        if active_only:
            query = query.where(AgentSession.is_active == True)

        count_result = await db.execute(
            select(func.count()).select_from(query.subquery())
        )
        total = count_result.scalar_one()

        active_count_result = await db.execute(
            select(func.count()).where(AgentSession.is_active == True)
        )
        active_count = active_count_result.scalar_one()

        result = await db.execute(
            query
            .order_by(AgentSession.connected_at.desc())
            .offset((page - 1) * per_page)
            .limit(per_page)
        )
        sessions = result.scalars().all()

        return SessionListResponse(
            sessions=[SessionSummarySchema.model_validate(s) for s in sessions],
            total=total,
            active_count=active_count,
        )
